package com.tp.multithreading;

/*
 * Every thread in Java has some default priority, it may be default priority generated by JVM or customized priority provided by programmer.
 * The valid range of thread priority is (1-10).
 * Default priority of ‘main’ thread is 5 and for all other threads default priority will be inherited from parent to child 
 * i.e whatever priority parent thread has same priority will be there in its child threads as well until we modify that explicitely.
 */
public class Part06_ThreadPriority {
	public static void main(String[] args) {
		Runnable r1 = () -> {
			Thread t = Thread.currentThread();
			System.out.println(t.getName() + " initial priority - " + t.getPriority());

			t.setPriority(8);
			Runnable cr = () -> {
				System.out.println(Thread.currentThread().getName() + " priority - " + Thread.currentThread().getPriority());
			};
			Thread ct = new Thread(cr);
			ct.start();

			System.out.println(t.getName() + " updated priority - " + t.getPriority());
		};

		System.out.println("Main thread initial priority : " + Thread.currentThread().getPriority());
		Thread t1 = new Thread(r1, "FirstChild");
		t1.start();

		Thread.currentThread().setPriority(3);
		System.out.println("Main thread updated priority : " + Thread.currentThread().getPriority());

		Thread t2 = new Thread(r1, "SecondChild");
		t2.start();
	}
}
